name: DemoApp

options:
  bundleIdPrefix: com.demo
  deploymentTarget:
    iOS: "17.0"

packages:
  InfiniteCarouselView:
    path: ../..

targets:
  DemoApp:
    type: application
    platform: iOS
    sources: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.demo.DemoApp
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        SWIFT_VERSION: "6.0"
    dependencies:
      - package: InfiniteCarouselView
